[package]
name = "claw-ql"
version = "0.1.0"
edition = "2024"

[dependencies]
claw-ql-macros = { path = "./claw-ql-macros", version = "0.1.0" }
sqlx = { version = "0.8.5" }
paste = "1.0.15"
# feature trace
tracing = { version = "0.1.40", optional = true }
# feature serde
serde_json = { version = "1.0.117", optional = true }
serde = { version = "1.0.203", optional = true }

[dev-dependencies]
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
tokio = { version = "1.37.0", features = ["full"] }
pretty_assertions = "1"
sqlx = { version = "0.8.5", features = ["runtime-tokio"] }

[features]
default = ["sqlite", "serde", "beta", "trace"]
waiting_min_specialization = []
beta = []
serde = ["dep:serde_json", "dep:serde"]
trace = ["dep:tracing"]
sqlite = ["sqlx/sqlite"]
